### ISSUE TITLE
InfluxDB-FritzBox not working

### ISSUE THREAD

**Issue by Camelot631** [TheCry/synology-fritzbox-grafana#1]
Hello ... seems to be quiet here ... nevertheless I still find this image to be the best for Synology NAS Docker ...
.
"InfluxDB-Synonlogy" works very well
"InfluxDB-FritzBox" does not work.

An error is displayed regarding "collectd" ..... could not be found ....

DSM 7.0.1-42218 (DS220 +)
Fritz! Box 5530 Fiber AON

Docker and this image installed according to instructions!

If required and this image is still maintained at all, screenshots are available ...

Greetings, Camelot 631

**Comment by TheCry** [comment]
Sorry for the delayed answer. Yes i will maintain this package.
Please attache the images. I will check the issue.
Edit: 
Did you upgrade the Debian packages inside the container?

**Comment by dfoerster79** [comment]
i have the same issue. i try to test the connection under database and get error "Influx DB Error: database not found: collectd"
![Screenshot 2022-01-10 215231](https://user-images.githubusercontent.com/46315137/148838836-336c16fd-a7e0-4793-8b9e-8358ba87d49f.png)

**Comment by TheCry** [comment]
The same question!
Did you upgrade the Debian packages inside the container?

**Comment by TheCry** [comment]
Same problem https://github.com/TheCry/synology-fritzbox-grafana/issues/2

**Comment by ProcusAquila** [comment]
Hello, is there already a correct solution to this, as it only says closed here?

I have exactly the same problem with the database.
I have gone through all the steps mentioned here.

Also with me:

Collectd Daemon is running
Directories and files are available, etc. but the "database" is not found, no communication with FB
Otherwise, I have already installed and uninstalled the Docker image several times. Created new users in FB, checked everything there. Restarted FB several times.

The Synology output runs without errors, Fritzbox N/A. Is it perhaps because the FB is a cable box (6490)? 

Private information: Writing in German is also possible
